### ISSUE TITLE
extract all times from all log files isn't working

### ISSUE THREAD

**Issue by xf0e** [karpathy/ulogme#13]
Hello, 

in file export_events.py on the line 54 the interpeter generates an exeption:

Traceback (most recent call last):
  File "export_events.py", line 117, in <module>
    updateEvents()
  File "export_events.py", line 54, in updateEvents
    ts = [int(x[x.find('_')+1:x.find('.txt')]) for x in L]
ValueError: invalid literal for int() with base 10:

**Comment by sld** [comment]
I did have the same error in OS X.
First time I run ./ulogme.sh by using python 3.3.
Then keyfreq_.txt become in logs/.
Then I got the same error described by @xf0e.

Deleting files in logs/ and rerun ./ulogme.sh by using python 2.7.8 fixed the problem.

**Comment by dannygoldstein** [comment]
Had a weird experience where `keyfreq_.txt` kept reappearing in `logs/` every couple seconds, causing `updateEvents()` to fail with 

    ts = [int(x[x.find('_')+1:x.find('.txt')]) for x in L]
    ValueError: invalid literal for int() with base 10:

 even though `ps -fA | grep ulogme` showed no active `./ulogme.sh` processes. Turned out there was a zombie `bash ulogme.sh` from hours before that was putting them there. If anyone keeps running into the invalid literal error, try doing a `ps -fA | grep bash` and killing old shells that may be running ulogme.
